/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2026-05-22 19:26:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.guest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hotel.model.*;
import com.hotel.model.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1779472911387L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1779472911388L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.hotel.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    Guest guest = (Guest) session.getAttribute("loggedInGuest");
    if (guest == null) { response.sendRedirect(request.getContextPath() + "/guests?action=login"); return; }
    String guestType = (guest instanceof VIPGuest) ? "VIP" : "Regular";
    String tier = (guest instanceof VIPGuest) ? ((VIPGuest)guest).getMembershipTier() : "N/A";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>My Profile - Grand Vista Hotel</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap & Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("    <!-- Animate.css for entrance animations -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Animated Gradient Background */\r\n");
      out.write("        .profile-wrapper {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            min-height: 90vh;\r\n");
      out.write("            background: linear-gradient(-45deg, #0f2027, #203a43, #2c5364, #1f4037, #99f2c8);\r\n");
      out.write("            background-size: 400% 400%;\r\n");
      out.write("            animation: gradientBG 15s ease infinite;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            padding: 40px 0;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes gradientBG {\r\n");
      out.write("            0% { background-position: 0% 50%; }\r\n");
      out.write("            50% { background-position: 100% 50%; }\r\n");
      out.write("            100% { background-position: 0% 50%; }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Glassmorphism Card */\r\n");
      out.write("        .glass-card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);\r\n");
      out.write("            backdrop-filter: blur(12px);\r\n");
      out.write("            -webkit-backdrop-filter: blur(12px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .glass-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 15px 35px rgba(0,0,0,0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Input Fields */\r\n");
      out.write("        .form-control {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.15) !important;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.3) !important;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            color: #fff !important;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control::placeholder {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control:focus {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.25) !important;\r\n");
      out.write("            box-shadow: 0 0 15px rgba(255, 255, 255, 0.5) !important;\r\n");
      out.write("            transform: scale(1.01);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Table Design - සුදු පාට අයින් කරලා Transparent කලා */\r\n");
      out.write("        .glass-table, .glass-table tr, .glass-table th, .glass-table td {\r\n");
      out.write("            background-color: transparent !important;\r\n");
      out.write("            --bs-table-bg: transparent !important;\r\n");
      out.write("        }\r\n");
      out.write("        .glass-table th { color: #99f2c8; font-weight: 600; border-bottom: 1px solid rgba(255,255,255,0.1); }\r\n");
      out.write("        .glass-table td { color: #ffffff; border-bottom: 1px solid rgba(255,255,255,0.1); }\r\n");
      out.write("\r\n");
      out.write("        /* Buttons */\r\n");
      out.write("        .btn-custom {\r\n");
      out.write("            background: linear-gradient(45deg, #00b4db, #0083b0);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: white;\r\n");
      out.write("            transition: 0.4s;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-custom:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(0, 180, 219, 0.5);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-danger-custom {\r\n");
      out.write("            background: linear-gradient(45deg, #cb2d3e, #ef473a);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: white;\r\n");
      out.write("            transition: 0.4s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-danger-custom:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(239, 71, 58, 0.5);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-outline-glass {\r\n");
      out.write("            border: 2px solid rgba(255,255,255,0.5);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            background: rgba(255,255,255,0.1);\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-outline-glass:hover {\r\n");
      out.write("            background: rgba(255,255,255,0.3);\r\n");
      out.write("            color: white;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Floating Bubbles */\r\n");
      out.write("        .bubbles {\r\n");
      out.write("            position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: 1; pointer-events: none;\r\n");
      out.write("        }\r\n");
      out.write("        .bubble {\r\n");
      out.write("            position: absolute; bottom: -100px; background: rgba(255, 255, 255, 0.1); border-radius: 50%;\r\n");
      out.write("            animation: rise 10s infinite ease-in;\r\n");
      out.write("        }\r\n");
      out.write("        .bubble:nth-child(1) { width: 40px; height: 40px; left: 10%; animation-duration: 8s; }\r\n");
      out.write("        .bubble:nth-child(2) { width: 20px; height: 20px; left: 20%; animation-duration: 5s; animation-delay: 1s; }\r\n");
      out.write("        .bubble:nth-child(3) { width: 50px; height: 50px; left: 35%; animation-duration: 10s; animation-delay: 2s; }\r\n");
      out.write("        .bubble:nth-child(4) { width: 80px; height: 80px; left: 50%; animation-duration: 14s; }\r\n");
      out.write("\r\n");
      out.write("        @keyframes rise {\r\n");
      out.write("            0% { bottom: -100px; transform: translateX(0); }\r\n");
      out.write("            50% { transform: translateX(30px); }\r\n");
      out.write("            100% { bottom: 100vh; transform: translateX(-30px); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 3D Profile Icon */\r\n");
      out.write("        .profile-icon {\r\n");
      out.write("            font-size: 6rem;\r\n");
      out.write("            background: -webkit-linear-gradient(45deg, #99f2c8, #1f4037);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            filter: drop-shadow(0px 5px 10px rgba(0,0,0,0.5));\r\n");
      out.write("            animation: float 4s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes float {\r\n");
      out.write("            0% { transform: translateY(0px); }\r\n");
      out.write("            50% { transform: translateY(-10px); }\r\n");
      out.write("            100% { transform: translateY(0px); }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Guest loggedInGuest = (Guest) session.getAttribute("loggedInGuest");
    Staff loggedInStaff = (Staff) session.getAttribute("loggedInStaff");
    String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-hotel navbar-dark\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print( contextPath );
      out.write("/index.jsp\">\r\n");
      out.write("            <i class=\"bi bi-building\"></i> Grand Vista Hotel\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarMain\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarMain\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=list\">\r\n");
      out.write("                        <i class=\"bi bi-door-open\"></i> Rooms\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=book\">\r\n");
      out.write("                        <i class=\"bi bi-calendar-plus\"></i> Book Now\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=view\">\r\n");
      out.write("                        <i class=\"bi bi-star\"></i> Reviews\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-gear\"></i> Management\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=dashboard\">Dashboard</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=list\">Guests</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">Payments</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=moderate\">Moderate Reviews</a></li>\r\n");
      out.write("                        ");
 if (loggedInStaff instanceof Manager) { 
      out.write("\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=add\">Add Room</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=manage\">Manage Staff</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                ");
 if (loggedInGuest != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-circle\"></i> ");
      out.print( loggedInGuest.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=profile\">My Profile</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">My Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">My Payments</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-badge\"></i> ");
      out.print( loggedInStaff.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><span class=\"dropdown-item-text text-muted small\">");
      out.print( loggedInStaff.getRole() );
      out.write("</span></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-box-arrow-in-right\"></i> Guest Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-shield-lock\"></i> Staff Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"profile-wrapper\">\r\n");
      out.write("    <!-- Floating Bubbles -->\r\n");
      out.write("    <div class=\"bubbles\">\r\n");
      out.write("        <div class=\"bubble\"></div><div class=\"bubble\"></div>\r\n");
      out.write("        <div class=\"bubble\"></div><div class=\"bubble\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container position-relative\" style=\"z-index: 10;\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Left Column: Profile Summary -->\r\n");
      out.write("            <div class=\"col-md-4 mb-4\">\r\n");
      out.write("                <div class=\"glass-card text-center p-4 animate__animated animate__fadeInLeft\">\r\n");
      out.write("                    <i class=\"bi bi-person-circle profile-icon\"></i>\r\n");
      out.write("                    <h4 class=\"mt-3 fw-bold text-uppercase\">");
      out.print( guest.getName() );
      out.write("</h4>\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"badge ");
      out.print( "VIP".equals(guestType) ? "bg-warning text-dark" : "bg-light text-dark" );
      out.write(" px-3 py-2 mt-2\" style=\"border-radius: 15px; font-size: 0.9rem;\">\r\n");
      out.write("                        <i class=\"bi bi-award-fill\"></i> ");
      out.print( guestType );
      out.write(" Guest\r\n");
      out.write("                    </span>\r\n");
      out.write("\r\n");
      out.write("                    ");
 if ("VIP".equals(guestType)) { 
      out.write("\r\n");
      out.write("                    <p class=\"mt-3 mb-0 text-light\">Membership Tier</p>\r\n");
      out.write("                    <h5 class=\"fw-bold\" style=\"color: #f1c40f;\">");
      out.print( tier );
      out.write("</h5>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <hr style=\"border-color: rgba(255,255,255,0.2); margin: 20px 0;\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center mb-2\">\r\n");
      out.write("                        <span><i class=\"bi bi-star-fill text-warning\"></i> Loyalty Points</span>\r\n");
      out.write("                        <strong class=\"fs-5\">");
      out.print( guest.getLoyaltyPoints() );
      out.write("</strong>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <span class=\"text-light small\"><i class=\"bi bi-tags\"></i> Discount Rate</span>\r\n");
      out.write("                        <strong class=\"text-success fs-5\">");
      out.print( (int)(guest.calculateDiscount()*100) );
      out.write("%</strong>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Right Column: Profile Form -->\r\n");
      out.write("            <div class=\"col-md-8\">\r\n");
      out.write("                <div class=\"glass-card p-4 animate__animated animate__fadeInRight\">\r\n");
      out.write("                    <h4 class=\"mb-4 border-bottom border-light pb-2\" style=\"border-color: rgba(255,255,255,0.1)!important;\">\r\n");
      out.write("                        <i class=\"bi bi-pencil-square\"></i> Profile Details\r\n");
      out.write("                    </h4>\r\n");
      out.write("\r\n");
      out.write("                    ");
 if (request.getAttribute("success") != null) { 
      out.write("\r\n");
      out.write("                    <div class=\"alert alert-success animate__animated animate__pulse\" style=\"background: rgba(25, 135, 84, 0.8); color: white; border: none;\">\r\n");
      out.write("                        <i class=\"bi bi-check-circle-fill\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${success}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("                    <div class=\"alert alert-danger animate__animated animate__shakeX\" style=\"background: rgba(220, 53, 69, 0.8); color: white; border: none;\">\r\n");
      out.write("                        <i class=\"bi bi-exclamation-triangle-fill\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <table class=\"table table-borderless glass-table mb-4\">\r\n");
      out.write("                        <tr><th width=\"30%\">Guest ID:</th><td><code style=\"background: rgba(0,0,0,0.5); padding: 5px 10px; border-radius: 5px; color: #99f2c8;\">");
      out.print( guest.getId() );
      out.write("</code></td></tr>\r\n");
      out.write("                        <tr><th>Email:</th><td>");
      out.print( guest.getEmail() );
      out.write("</td></tr>\r\n");
      out.write("                        <tr><th>Phone:</th><td>");
      out.print( guest.getPhone() != null ? guest.getPhone() : "Not set" );
      out.write("</td></tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("                    <h5 class=\"mt-4 mb-3 text-light\">Update Profile</h5>\r\n");
      out.write("\r\n");
      out.write("                    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/guests\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"profile\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label text-light\"><i class=\"bi bi-person\"></i> Full Name</label>\r\n");
      out.write("                                <input type=\"text\" name=\"name\" class=\"form-control\" value=\"");
      out.print( guest.getName() );
      out.write("\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label text-light\"><i class=\"bi bi-envelope\"></i> Email</label>\r\n");
      out.write("                                <input type=\"email\" name=\"email\" class=\"form-control\" value=\"");
      out.print( guest.getEmail() );
      out.write("\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label text-light\"><i class=\"bi bi-telephone\"></i> Phone Number</label>\r\n");
      out.write("                                <input type=\"tel\" name=\"phone\" class=\"form-control\" value=\"");
      out.print( guest.getPhone() != null ? guest.getPhone() : "" );
      out.write("\"\r\n");
      out.write("                                       maxlength=\"12\" pattern=\"^\\+[0-9]{11}$\"\r\n");
      out.write("                                       title=\"Must start with '+' followed by country code and 11 digits total\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label text-light\"><i class=\"bi bi-key\"></i> New Password</label>\r\n");
      out.write("                                <input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Leave blank to keep current\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-custom px-4 mt-2\">\r\n");
      out.write("                            <i class=\"bi bi-save\"></i> Save Changes\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Action Buttons -->\r\n");
      out.write("                <div class=\"row mt-4 animate__animated animate__fadeInUp\" style=\"animation-delay: 0.5s;\">\r\n");
      out.write("                    <div class=\"col-sm-5 mb-2\">\r\n");
      out.write("                        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/guests\" method=\"post\"\r\n");
      out.write("                              onsubmit=\"return confirm('Are you sure you want to permanently delete your account? This action cannot be undone.');\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"selfDelete\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-danger-custom w-100 py-2\">\r\n");
      out.write("                                <i class=\"bi bi-trash-fill\"></i> Delete Account\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-sm-7\">\r\n");
      out.write("                        <div class=\"d-flex gap-2\">\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=list\"\r\n");
      out.write("                               class=\"btn btn-outline-glass w-50 py-2\">\r\n");
      out.write("                                <i class=\"bi bi-calendar-check\"></i> Reservations\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/payments?action=history\"\r\n");
      out.write("                               class=\"btn btn-outline-glass w-50 py-2\">\r\n");
      out.write("                                <i class=\"bi bi-receipt\"></i> Payments\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h5 style=\"color: #c9a84c;\"><i class=\"bi bi-building\"></i> Grand Vista Hotel</h5>\r\n");
      out.write("                <p class=\"small\">Luxury and comfort, perfectly blended for an unforgettable stay.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h6 class=\"text-white\">Quick Links</h6>\r\n");
      out.write("                <ul class=\"list-unstyled small\">\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/rooms?action=list\">Browse Rooms</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=book\">Make a Reservation</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reviews?action=view\">Guest Reviews</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h6 class=\"text-white\">Contact</h6>\r\n");
      out.write("                <p class=\"small\">\r\n");
      out.write("                    <i class=\"bi bi-geo-alt\"></i> 123 Grand Vista Blvd<br>\r\n");
      out.write("                    <i class=\"bi bi-telephone\"></i> +94 (70) 584-5628<br>\r\n");
      out.write("                    <i class=\"bi bi-envelope\"></i> info@grandvista.com\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr style=\"border-color: rgba(255,255,255,0.2);\">\r\n");
      out.write("        <p class=\"text-center small mb-0\">&copy; 2026 Grand Vista Hotel. All rights reserved | Website Design by SLIIT-KdyUni-G54-2026-SEM-2 (FOC)</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
