/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2026-05-23 03:57:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hotel.model.*;
import com.hotel.model.*;

public final class book_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/C:/Users/Admin/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1771869617414L));
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1778867051865L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1778867051865L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.hotel.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Book a Room - Grand Vista Hotel</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .booking-hero {\r\n");
      out.write("            background: linear-gradient(135deg, var(--hotel-primary) 0%, #2d6a9f 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 40px 0 60px;\r\n");
      out.write("            margin-bottom: -30px;\r\n");
      out.write("        }\r\n");
      out.write("        .booking-card {\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(26,60,94,0.18);\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("        .step-badge {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            width: 32px;\r\n");
      out.write("            height: 32px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background: var(--hotel-primary);\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            flex-shrink: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .step-title {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            color: var(--hotel-primary);\r\n");
      out.write("            margin-bottom: 16px;\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("            border-bottom: 2px solid #e8edf2;\r\n");
      out.write("        }\r\n");
      out.write("        .room-card-option {\r\n");
      out.write("            border: 2px solid #dee2e6;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 14px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.2s;\r\n");
      out.write("            background: white;\r\n");
      out.write("        }\r\n");
      out.write("        .room-card-option:hover,\r\n");
      out.write("        .room-card-option.selected {\r\n");
      out.write("            border-color: var(--hotel-primary);\r\n");
      out.write("            background: #eef3f8;\r\n");
      out.write("        }\r\n");
      out.write("        .price-summary {\r\n");
      out.write("            background: linear-gradient(135deg, #eef3f8, #dce8f5);\r\n");
      out.write("            border: 1px solid #b8d0e8;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .price-row {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("        }\r\n");
      out.write("        .price-row.total {\r\n");
      out.write("            border-top: 2px solid var(--hotel-primary);\r\n");
      out.write("            padding-top: 12px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            color: var(--hotel-primary);\r\n");
      out.write("        }\r\n");
      out.write("        .discount-badge {\r\n");
      out.write("            background: #d4edda;\r\n");
      out.write("            color: #155724;\r\n");
      out.write("            padding: 2px 8px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 0.8rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .form-control:focus, .form-select:focus {\r\n");
      out.write("            border-color: var(--hotel-primary);\r\n");
      out.write("            box-shadow: 0 0 0 0.2rem rgba(26,60,94,0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-book {\r\n");
      out.write("            background: linear-gradient(135deg, var(--hotel-primary), #2d6a9f);\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 14px 32px;\r\n");
      out.write("            font-size: 1.05rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            transition: all 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-book:hover:not(:disabled) {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 6px 20px rgba(26,60,94,0.35);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-book:disabled { opacity: 0.6; cursor: not-allowed; }\r\n");
      out.write("        .nights-pill {\r\n");
      out.write("            background: var(--hotel-secondary);\r\n");
      out.write("            color: var(--hotel-dark);\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            padding: 3px 12px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("        }\r\n");
      out.write("        .validation-feedback { font-size: 0.82rem; }\r\n");
      out.write("        .char-counter { font-size: 0.78rem; color: #6c757d; float: right; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Guest loggedInGuest = (Guest) session.getAttribute("loggedInGuest");
    Staff loggedInStaff = (Staff) session.getAttribute("loggedInStaff");
    String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-hotel navbar-dark\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print( contextPath );
      out.write("/index.jsp\">\r\n");
      out.write("            <i class=\"bi bi-building\"></i> Grand Vista Hotel\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarMain\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarMain\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=list\">\r\n");
      out.write("                        <i class=\"bi bi-door-open\"></i> Rooms\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=book\">\r\n");
      out.write("                        <i class=\"bi bi-calendar-plus\"></i> Book Now\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=view\">\r\n");
      out.write("                        <i class=\"bi bi-star\"></i> Reviews\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-gear\"></i> Management\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=dashboard\">Dashboard</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=list\">Guests</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">Payments</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=moderate\">Moderate Reviews</a></li>\r\n");
      out.write("                        ");
 if (loggedInStaff instanceof Manager) { 
      out.write("\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=add\">Add Room</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=manage\">Manage Staff</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                ");
 if (loggedInGuest != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-circle\"></i> ");
      out.print( loggedInGuest.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=profile\">My Profile</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">My Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">My Payments</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-badge\"></i> ");
      out.print( loggedInStaff.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><span class=\"dropdown-item-text text-muted small\">");
      out.print( loggedInStaff.getRole() );
      out.write("</span></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-box-arrow-in-right\"></i> Guest Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-shield-lock\"></i> Staff Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Guest loggedGuest = (Guest) session.getAttribute("loggedInGuest");
    String guestIdVal = (loggedGuest != null) ? loggedGuest.getId() : "";
    if (request.getAttribute("prevGuestId") != null && ((String)request.getAttribute("prevGuestId")).length() > 0)
        guestIdVal = (String) request.getAttribute("prevGuestId");
    double discountRate = (loggedGuest != null) ? loggedGuest.calculateDiscount() : 0.0;
    int discountPct = (int)(discountRate * 100);
    String guestType = (loggedGuest instanceof VIPGuest) ? "VIP" : "Regular";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Hero Banner -->\r\n");
      out.write("<div class=\"booking-hero\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("            <ol class=\"breadcrumb mb-2\" style=\"--bs-breadcrumb-divider-color: rgba(255,255,255,0.5);\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"text-white-50\">Home</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=list\" class=\"text-white-50\">Reservations</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active text-white\">Book a Room</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <h2 class=\"fw-bold mb-1\"><i class=\"bi bi-calendar-plus me-2\"></i>Make a Reservation</h2>\r\n");
      out.write("        <p class=\"opacity-75 mb-0\">Complete the form below to reserve your ideal room</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-5\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Alert messages -->\r\n");
      out.write("    ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-danger alert-dismissible fade show mb-4\" role=\"alert\">\r\n");
      out.write("        <i class=\"bi bi-exclamation-triangle-fill me-2\"></i>\r\n");
      out.write("        <strong>Booking Error:</strong> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("        <!-- Main Form -->\r\n");
      out.write("        <div class=\"col-lg-7\">\r\n");
      out.write("            <div class=\"card booking-card\">\r\n");
      out.write("                <div class=\"card-body p-4\">\r\n");
      out.write("\r\n");
      out.write("                    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations\"\r\n");
      out.write("                          method=\"post\" id=\"bookForm\" novalidate>\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"book\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Step 1: Guest -->\r\n");
      out.write("                        <div class=\"step-title\">\r\n");
      out.write("                            <span class=\"step-badge\">1</span> Guest Information\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-4\">\r\n");
      out.write("                            <label class=\"form-label fw-semibold\">Guest ID <span class=\"text-danger\">*</span></label>\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <span class=\"input-group-text bg-light\"><i class=\"bi bi-person-badge\"></i></span>\r\n");
      out.write("                                <input type=\"text\" name=\"guestId\" id=\"guestId\"\r\n");
      out.write("                                       class=\"form-control\"\r\n");
      out.write("                                       value=\"");
      out.print( guestIdVal );
      out.write("\"\r\n");
      out.write("                                       ");
      out.print( loggedGuest != null ? "readonly" : "" );
      out.write("\r\n");
      out.write("                                       placeholder=\"e.g. G123456789\"\r\n");
      out.write("                                       pattern=\"[A-Za-z0-9]+\" required>\r\n");
      out.write("                                <div class=\"invalid-feedback validation-feedback\">Please enter a valid Guest ID.</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 if (loggedGuest != null) { 
      out.write("\r\n");
      out.write("                            <div class=\"mt-2\">\r\n");
      out.write("                                <i class=\"bi bi-check-circle-fill text-success me-1\"></i>\r\n");
      out.write("                                <strong>");
      out.print( loggedGuest.getName() );
      out.write("</strong>\r\n");
      out.write("                                ");
 if (discountPct > 0) { 
      out.write("\r\n");
      out.write("                                &nbsp;<span class=\"discount-badge\">");
      out.print( guestType );
      out.write(' ');
      out.write('–');
      out.write(' ');
      out.print( discountPct );
      out.write("% discount applied</span>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                            <div class=\"form-text\">\r\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/guests?action=login\">\r\n");
      out.write("                                    <i class=\"bi bi-box-arrow-in-right\"></i> Log in\r\n");
      out.write("                                </a> to auto-fill and unlock member discounts.\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Step 2: Room -->\r\n");
      out.write("                         <div class=\"step-title\">\r\n");
      out.write("                             <span class=\"step-badge\">2</span> Select Room\r\n");
      out.write("                         </div>\r\n");
      out.write("                        <div class=\"mb-4\">\r\n");
      out.write("                            <label class=\"form-label fw-semibold\">Available Rooms <span class=\"text-danger\">*</span></label>\r\n");
      out.write("                            <select name=\"roomNumber\" id=\"roomSelect\" class=\"form-select\" required\r\n");
      out.write("                                     onchange=\"onRoomChange()\">\r\n");
      out.write("                                <option value=\"\">-- Choose a room --</option>\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <div id=\"roomDetails\" class=\"mt-2 text-muted small\" style=\"display:none;\">\r\n");
      out.write("                                 <i class=\"bi bi-info-circle\"></i> <span id=\"roomAmenities\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"invalid-feedback validation-feedback\">Please select a room.</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Step 3: Dates -->\r\n");
      out.write("                         <div class=\"step-title\">\r\n");
      out.write("                             <span class=\"step-badge\">3</span> Stay Dates\r\n");
      out.write("                         </div>\r\n");
      out.write("                        <div class=\"row g-3 mb-4\">\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <label class=\"form-label fw-semibold\">Check-In <span class=\"text-danger\">*</span></label>\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-text bg-light\"><i class=\"bi bi-calendar-event\"></i></span>\r\n");
      out.write("                                    <input type=\"date\" name=\"checkIn\" id=\"checkIn\"\r\n");
      out.write("                                           class=\"form-control\"\r\n");
      out.write("                                           min=\"");
      out.print( java.time.LocalDate.now() );
      out.write("\"\r\n");
      out.write("                                           value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prevCheckIn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                           required onchange=\"calcTotal()\">\r\n");
      out.write("                                    <div class=\"invalid-feedback validation-feedback\">Select a valid check-in date.</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <label class=\"form-label fw-semibold\">Check-Out <span class=\"text-danger\">*</span></label>\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-text bg-light\"><i class=\"bi bi-calendar-check\"></i></span>\r\n");
      out.write("                                    <input type=\"date\" name=\"checkOut\" id=\"checkOut\"\r\n");
      out.write("                                           class=\"form-control\"\r\n");
      out.write("                                           min=\"");
      out.print( java.time.LocalDate.now().plusDays(1) );
      out.write("\"\r\n");
      out.write("                                           value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prevCheckOut}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                           required onchange=\"calcTotal()\">\r\n");
      out.write("                                    <div class=\"invalid-feedback validation-feedback\">Select a valid check-out date.</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Step 4: Special Requests -->\r\n");
      out.write("                         <div class=\"step-title\">\r\n");
      out.write("                             <span class=\"step-badge\">4</span> Special Requests\r\n");
      out.write("                             <span class=\"badge bg-secondary fw-normal ms-2\" style=\"font-size:0.7rem;\">Optional</span>\r\n");
      out.write("                         </div>\r\n");
      out.write("                        <div class=\"mb-4\">\r\n");
      out.write("                            <textarea name=\"specialRequests\" id=\"specialRequests\"\r\n");
      out.write("                                      class=\"form-control\" rows=\"3\" maxlength=\"300\"\r\n");
      out.write("                                      placeholder=\"e.g. Late check-in, extra pillows, high floor preference…\"\r\n");
      out.write("                                      onkeyup=\"updateCharCount()\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prevSpecial}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                            <div><span class=\"char-counter\"><span id=\"charCount\">0</span>/300</span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"d-grid\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-book\" id=\"submitBtn\" disabled>\r\n");
      out.write("                                <i class=\"bi bi-check-circle me-2\"></i>Confirm Reservation\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar: Price Summary -->\r\n");
      out.write("        <div class=\"col-lg-5\">\r\n");
      out.write("            <div class=\"sticky-top\" style=\"top: 80px;\">\r\n");
      out.write("                <!-- Price Summary -->\r\n");
      out.write("                <div class=\"card booking-card mb-3\" id=\"priceSummaryCard\" style=\"display:none !important;\">\r\n");
      out.write("                    <div class=\"card-header card-header-hotel\">\r\n");
      out.write("                        <h6 class=\"mb-0\"><i class=\"bi bi-receipt me-2\"></i>Booking Summary</h6>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body p-3\">\r\n");
      out.write("                        <div class=\"price-summary\">\r\n");
      out.write("                            <div class=\"price-row\">\r\n");
      out.write("                                <span class=\"text-muted\">Room</span>\r\n");
      out.write("                                <span id=\"summaryRoom\" class=\"fw-semibold\">—</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"price-row\">\r\n");
      out.write("                                <span class=\"text-muted\">Duration</span>\r\n");
      out.write("                                <span id=\"summaryNights\">—</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"price-row\">\r\n");
      out.write("                                <span class=\"text-muted\">Rate / night</span>\r\n");
      out.write("                                <span id=\"summaryRate\">—</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"price-row\">\r\n");
      out.write("                                <span class=\"text-muted\">Subtotal</span>\r\n");
      out.write("                                <span id=\"summarySubtotal\">—</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 if (discountPct > 0) { 
      out.write("\r\n");
      out.write("                            <div class=\"price-row text-success\">\r\n");
      out.write("                                <span><i class=\"bi bi-tag-fill me-1\"></i>");
      out.print( guestType );
      out.write(" discount</span>\r\n");
      out.write("                                <span>-");
      out.print( discountPct );
      out.write("%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                            <div class=\"price-row total\">\r\n");
      out.write("                                <span>Total</span>\r\n");
      out.write("                                <span id=\"summaryTotal\">—</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h5 style=\"color: #c9a84c;\"><i class=\"bi bi-building\"></i> Grand Vista Hotel</h5>\r\n");
      out.write("                <p class=\"small\">Luxury and comfort, perfectly blended for an unforgettable stay.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h6 class=\"text-white\">Quick Links</h6>\r\n");
      out.write("                <ul class=\"list-unstyled small\">\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/rooms?action=list\">Browse Rooms</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=book\">Make a Reservation</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reviews?action=view\">Guest Reviews</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h6 class=\"text-white\">Contact</h6>\r\n");
      out.write("                <p class=\"small\">\r\n");
      out.write("                    <i class=\"bi bi-geo-alt\"></i> 123 Grand Vista Blvd<br>\r\n");
      out.write("                    <i class=\"bi bi-telephone\"></i> +94 (70) 584-5628<br>\r\n");
      out.write("                    <i class=\"bi bi-envelope\"></i> info@grandvista.com\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr style=\"border-color: rgba(255,255,255,0.2);\">\r\n");
      out.write("        <p class=\"text-center small mb-0\">&copy; 2026 Grand Vista Hotel. All rights reserved | Website Design by SLIIT-KdyUni-G54-2026-SEM-2 (FOC)</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    var discount = ");
      out.print( discountRate );
      out.write(";\r\n");
      out.write("    var MIN_DATE = '");
      out.print( java.time.LocalDate.now() );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("    function onRoomChange() {\r\n");
      out.write("        var sel = document.getElementById('roomSelect');\r\n");
      out.write("        var opt = sel.selectedOptions[0];\r\n");
      out.write("        var roomDetails = document.getElementById('roomDetails');\r\n");
      out.write("        if (sel.value && opt.dataset.amenities) {\r\n");
      out.write("            document.getElementById('roomAmenities').textContent = opt.dataset.amenities;\r\n");
      out.write("            roomDetails.style.display = 'block';\r\n");
      out.write("        } else {\r\n");
      out.write("            roomDetails.style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("        calcTotal();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function calcTotal() {\r\n");
      out.write("        var roomSel  = document.getElementById('roomSelect');\r\n");
      out.write("        var checkIn  = document.getElementById('checkIn').value;\r\n");
      out.write("        var checkOut = document.getElementById('checkOut').value;\r\n");
      out.write("        var card     = document.getElementById('priceSummaryCard');\r\n");
      out.write("        var btn      = document.getElementById('submitBtn');\r\n");
      out.write("\r\n");
      out.write("        // Enforce checkOut > checkIn\r\n");
      out.write("        if (checkIn) {\r\n");
      out.write("            var nextDay = new Date(checkIn);\r\n");
      out.write("            nextDay.setDate(nextDay.getDate() + 1);\r\n");
      out.write("            document.getElementById('checkOut').min = nextDay.toISOString().split('T')[0];\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (roomSel.value && checkIn && checkOut) {\r\n");
      out.write("            var price  = parseFloat(roomSel.selectedOptions[0].dataset.price);\r\n");
      out.write("            var msDay  = 86400000;\r\n");
      out.write("            var nights = Math.round((new Date(checkOut) - new Date(checkIn)) / msDay);\r\n");
      out.write("\r\n");
      out.write("            if (nights > 0 && nights <= 90) {\r\n");
      out.write("                var subtotal = price * nights;\r\n");
      out.write("                var total    = subtotal * (1 - discount);\r\n");
      out.write("\r\n");
      out.write("                document.getElementById('summaryRoom').textContent     = 'Room ' + roomSel.value;\r\n");
      out.write("                document.getElementById('summaryNights').innerHTML     = nights + ' night' + (nights > 1 ? 's' : '') +\r\n");
      out.write("                    ' <span class=\"nights-pill\">' + nights + 'N</span>';\r\n");
      out.write("                document.getElementById('summaryRate').textContent     = '$' + price.toFixed(2);\r\n");
      out.write("                document.getElementById('summarySubtotal').textContent = '$' + subtotal.toFixed(2);\r\n");
      out.write("                document.getElementById('summaryTotal').textContent    = '$' + total.toFixed(2);\r\n");
      out.write("\r\n");
      out.write("                card.style.removeProperty('display');\r\n");
      out.write("                btn.disabled = false;\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        card.style.display = 'none !important';\r\n");
      out.write("        btn.disabled = true;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function updateCharCount() {\r\n");
      out.write("        var ta = document.getElementById('specialRequests');\r\n");
      out.write("        document.getElementById('charCount').textContent = ta.value.length;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Bootstrap validation\r\n");
      out.write("    document.getElementById('bookForm').addEventListener('submit', function(e) {\r\n");
      out.write("        if (!this.checkValidity()) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            e.stopPropagation();\r\n");
      out.write("        }\r\n");
      out.write("        this.classList.add('was-validated');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Init on page load (handles back-navigation with values)\r\n");
      out.write("    window.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        onRoomChange();\r\n");
      out.write("        calcTotal();\r\n");
      out.write("        updateCharCount();\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /reservation/book.jsp(212,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fforEach_005f0.setVar("room");
    // /reservation/book.jsp(212,32) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/reservation/book.jsp(212,32) '${availableRooms}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${availableRooms}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                    <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.roomNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                             data-price=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.calculatePrice()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                             data-type=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                             data-floor=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.floor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                             data-amenities=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.amenities}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                             ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(not empty param.prevRoom and param.prevRoom == room.roomNumber) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(">\r\n");
          out.write("                                         Room ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.roomNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" &mdash; ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(", Floor ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.floor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" &mdash; $<fmt:formatNumber value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${room.calculatePrice()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" pattern=\"#,##0.00\" xmlns:fmt=\"http://java.sun.com/jsp/jstl/fmt\"/> / night\r\n");
          out.write("                                     </option>\r\n");
          out.write("                                ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
