/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2026-05-18 11:06:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hotel.model.*;
import com.hotel.model.*;

public final class modify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1778867051865L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1778867051865L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.hotel.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    Reservation res = (Reservation) request.getAttribute("reservation");
    if (res == null) { response.sendRedirect(request.getContextPath() + "/reservations?action=list"); return; }
    boolean isStaff   = session.getAttribute("loggedInStaff") != null;
    boolean isEditable = res.getStatus() != Reservation.Status.CANCELLED
                      && res.getStatus() != Reservation.Status.CHECKED_OUT;
    String statusCss   = res.getStatus().name();
    long nights        = res.getNights();
    String cancelFeeStr = String.format("%.2f", res.calculateCancellationFee());
    String resIdStr     = res.getReservationId();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Modify Reservation - Grand Vista Hotel</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .page-header {\r\n");
      out.write("            background: linear-gradient(135deg, var(--hotel-primary), #2d6a9f);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 32px 0 50px;\r\n");
      out.write("            margin-bottom: -24px;\r\n");
      out.write("        }\r\n");
      out.write("        .detail-card { border-radius: 14px; border: none; box-shadow: 0 4px 20px rgba(26,60,94,0.12); }\r\n");
      out.write("        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px 24px; }\r\n");
      out.write("        .info-item label { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.5px; color: #6c757d; font-weight: 600; margin-bottom: 2px; }\r\n");
      out.write("        .info-item .val  { font-weight: 600; font-size: 0.95rem; }\r\n");
      out.write("        .status-badge {\r\n");
      out.write("            display: inline-flex; align-items: center; gap: 5px;\r\n");
      out.write("            padding: 5px 12px; border-radius: 20px; font-weight: 600; font-size: 0.8rem;\r\n");
      out.write("        }\r\n");
      out.write("        .s-PENDING    { background:#fff3cd; color:#856404; }\r\n");
      out.write("        .s-CONFIRMED  { background:#d1e7dd; color:#0f5132; }\r\n");
      out.write("        .s-CHECKED_IN { background:#cff4fc; color:#055160; }\r\n");
      out.write("        .s-CHECKED_OUT{ background:#e2e3e5; color:#383d41; }\r\n");
      out.write("        .s-CANCELLED  { background:#f8d7da; color:#842029; }\r\n");
      out.write("        .form-control:focus, .form-select:focus {\r\n");
      out.write("            border-color: var(--hotel-primary);\r\n");
      out.write("            box-shadow: 0 0 0 0.2rem rgba(26,60,94,0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .section-label {\r\n");
      out.write("            font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.5px;\r\n");
      out.write("            color: var(--hotel-primary); font-weight: 700;\r\n");
      out.write("            margin-bottom: 12px; padding-bottom: 8px;\r\n");
      out.write("            border-bottom: 2px solid #e0e8f0;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-update {\r\n");
      out.write("            background: linear-gradient(135deg, var(--hotel-primary), #2d6a9f);\r\n");
      out.write("            color: white; border: none; border-radius: 8px;\r\n");
      out.write("            padding: 12px 28px; font-weight: 600; transition: all 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-update:hover { transform: translateY(-1px); box-shadow: 0 4px 16px rgba(26,60,94,0.3); color: white; }\r\n");
      out.write("        .new-total { color: var(--hotel-primary); font-weight: 700; font-size: 1.05rem; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Guest loggedInGuest = (Guest) session.getAttribute("loggedInGuest");
    Staff loggedInStaff = (Staff) session.getAttribute("loggedInStaff");
    String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-hotel navbar-dark\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print( contextPath );
      out.write("/index.jsp\">\r\n");
      out.write("            <i class=\"bi bi-building\"></i> Grand Vista Hotel\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarMain\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarMain\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=list\">\r\n");
      out.write("                        <i class=\"bi bi-door-open\"></i> Rooms\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=book\">\r\n");
      out.write("                        <i class=\"bi bi-calendar-plus\"></i> Book Now\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=view\">\r\n");
      out.write("                        <i class=\"bi bi-star\"></i> Reviews\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-gear\"></i> Management\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=dashboard\">Dashboard</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=list\">Guests</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">Payments</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=moderate\">Moderate Reviews</a></li>\r\n");
      out.write("                        ");
 if (loggedInStaff instanceof Manager) { 
      out.write("\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=add\">Add Room</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=manage\">Manage Staff</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                ");
 if (loggedInGuest != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-circle\"></i> ");
      out.print( loggedInGuest.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=profile\">My Profile</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">My Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">My Payments</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-badge\"></i> ");
      out.print( loggedInStaff.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><span class=\"dropdown-item-text text-muted small\">");
      out.print( loggedInStaff.getRole() );
      out.write("</span></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-box-arrow-in-right\"></i> Guest Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-shield-lock\"></i> Staff Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("            <ol class=\"breadcrumb mb-1\" style=\"--bs-breadcrumb-divider-color:rgba(255,255,255,0.4);\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"text-white-50\">Home</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=list\" class=\"text-white-50\">Reservations</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active text-white\">Modify</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <h3 class=\"fw-bold mb-0\"><i class=\"bi bi-pencil-square me-2\"></i>Modify Reservation</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-5\">\r\n");
      out.write("\r\n");
      out.write("    ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-danger alert-dismissible fade show mb-4\" role=\"alert\">\r\n");
      out.write("        <i class=\"bi bi-exclamation-triangle-fill me-2\"></i>\r\n");
      out.write("        <strong>Error:</strong> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("        <!-- Current Info Panel -->\r\n");
      out.write("        <div class=\"col-lg-4\">\r\n");
      out.write("            <div class=\"card detail-card h-100\">\r\n");
      out.write("                <div class=\"card-header card-header-hotel\">\r\n");
      out.write("                    <h6 class=\"mb-0\"><i class=\"bi bi-info-circle me-2\"></i>Current Details</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body p-4\">\r\n");
      out.write("                    <div class=\"info-grid mb-4\">\r\n");
      out.write("                        <div class=\"info-item\">\r\n");
      out.write("                            <label>Reservation ID</label>\r\n");
      out.write("                            <div class=\"val\" style=\"font-family:monospace; font-size:0.82rem; color:var(--hotel-primary);\">\r\n");
      out.write("                                ");
      out.print( res.getReservationId() );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"info-item\">\r\n");
      out.write("                            <label>Status</label>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span class=\"status-badge s-");
      out.print( statusCss );
      out.write("\">\r\n");
      out.write("                                    ");
 if (res.getStatus() == Reservation.Status.PENDING)     { 
      out.write("<i class=\"bi bi-clock-fill\"></i>\r\n");
      out.write("                                    ");
 } else if (res.getStatus() == Reservation.Status.CONFIRMED)  { 
      out.write("<i class=\"bi bi-check-circle-fill\"></i>\r\n");
      out.write("                                    ");
 } else if (res.getStatus() == Reservation.Status.CHECKED_IN) { 
      out.write("<i class=\"bi bi-door-open-fill\"></i>\r\n");
      out.write("                                    ");
 } else { 
      out.write("<i class=\"bi bi-x-circle-fill\"></i>");
 } 
      out.write("\r\n");
      out.write("                                    ");
      out.print( res.getStatus() );
      out.write("\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"info-item\">\r\n");
      out.write("                            <label>Room</label>\r\n");
      out.write("                            <div class=\"val\">Room ");
      out.print( res.getRoomNumber() );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"info-item\">\r\n");
      out.write("                            <label>Nights</label>\r\n");
      out.write("                            <div class=\"val\">");
      out.print( nights );
      out.write(" night");
      out.print( nights != 1 ? "s" : "" );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"info-item\">\r\n");
      out.write("                            <label>Check-In</label>\r\n");
      out.write("                            <div class=\"val\">");
      out.print( res.getCheckIn() != null ? res.getCheckIn() : "—" );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"info-item\">\r\n");
      out.write("                            <label>Check-Out</label>\r\n");
      out.write("                            <div class=\"val\">");
      out.print( res.getCheckOut() != null ? res.getCheckOut() : "—" );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"section-label\">Current Total</div>\r\n");
      out.write("                    <div style=\"font-size:1.5rem; font-weight:700; color:#1a6b3c;\">\r\n");
      out.write("                        $");
      out.print( String.format("%.2f", res.getTotalAmount()) );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
 if (res.getSpecialRequests() != null && !res.getSpecialRequests().isEmpty()) { 
      out.write("\r\n");
      out.write("                    <div class=\"mt-3\">\r\n");
      out.write("                        <div class=\"section-label\">Special Requests</div>\r\n");
      out.write("                        <p class=\"text-muted small mb-0\">");
      out.print( res.getSpecialRequests() );
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
 if (res.getCreatedAt() != null && !res.getCreatedAt().isEmpty()) { 
      out.write("\r\n");
      out.write("                    <div class=\"mt-3\">\r\n");
      out.write("                        <small class=\"text-muted\"><i class=\"bi bi-clock-history me-1\"></i>Booked: ");
      out.print( res.getCreatedAt() );
      out.write("</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Edit Form -->\r\n");
      out.write("        <div class=\"col-lg-8\">\r\n");
      out.write("            <div class=\"card detail-card\">\r\n");
      out.write("                <div class=\"card-header card-header-hotel\">\r\n");
      out.write("                    <h6 class=\"mb-0\"><i class=\"bi bi-sliders me-2\"></i>Update Reservation</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body p-4\">\r\n");
      out.write("\r\n");
      out.write("                    ");
 if (!isEditable) { 
      out.write("\r\n");
      out.write("                    <div class=\"alert alert-warning\">\r\n");
      out.write("                        <i class=\"bi bi-lock-fill me-2\"></i>\r\n");
      out.write("                        This reservation is <strong>");
      out.print( res.getStatus().name().toLowerCase() );
      out.write("</strong>\r\n");
      out.write("                        and cannot be modified.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations\"\r\n");
      out.write("                          method=\"post\" id=\"modifyForm\" novalidate>\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"modify\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"reservationId\" value=\"");
      out.print( res.getReservationId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Dates -->\r\n");
      out.write("                        <div class=\"section-label\"><i class=\"bi bi-calendar-range me-1\"></i>Update Stay Dates</div>\r\n");
      out.write("                        <div class=\"row g-3 mb-4\">\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <label class=\"form-label fw-semibold\">New Check-In Date</label>\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-text bg-light\"><i class=\"bi bi-calendar-event\"></i></span>\r\n");
      out.write("                                    <input type=\"date\" name=\"checkIn\" id=\"checkIn\" class=\"form-control\"\r\n");
      out.write("                                           value=\"");
      out.print( res.getCheckIn() != null ? res.getCheckIn() : "" );
      out.write("\"\r\n");
      out.write("                                           min=\"");
      out.print( java.time.LocalDate.now() );
      out.write("\"\r\n");
      out.write("                                           onchange=\"onCheckInChange()\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"checkInError\" class=\"text-danger small mt-1\" style=\"display:none;\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <label class=\"form-label fw-semibold\">New Check-Out Date</label>\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-text bg-light\"><i class=\"bi bi-calendar-check\"></i></span>\r\n");
      out.write("                                    <input type=\"date\" name=\"checkOut\" id=\"checkOut\" class=\"form-control\"\r\n");
      out.write("                                           value=\"");
      out.print( res.getCheckOut() != null ? res.getCheckOut() : "" );
      out.write("\"\r\n");
      out.write("                                           min=\"");
      out.print( java.time.LocalDate.now().plusDays(1) );
      out.write("\"\r\n");
      out.write("                                           onchange=\"calcNewTotal()\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"checkOutError\" class=\"text-danger small mt-1\" style=\"display:none;\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Live recalculation preview -->\r\n");
      out.write("                        <div id=\"newTotalDiv\" class=\"alert alert-info mb-4\" style=\"display:none;\">\r\n");
      out.write("                            <i class=\"bi bi-calculator me-2\"></i>\r\n");
      out.write("                            New estimated total: <span id=\"newTotalVal\" class=\"new-total\"></span>\r\n");
      out.write("                            <small class=\"d-block text-muted mt-1\">(based on current room rate; final amount calculated on save)</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Special Requests -->\r\n");
      out.write("                        <div class=\"section-label\"><i class=\"bi bi-chat-text me-1\"></i>Special Requests</div>\r\n");
      out.write("                        <div class=\"mb-4\">\r\n");
      out.write("                            <textarea name=\"specialRequests\" class=\"form-control\" rows=\"3\" maxlength=\"300\"\r\n");
      out.write("                                      placeholder=\"Update special requests (optional)\">");
      out.print( res.getSpecialRequests() );
      out.write("</textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Status (staff only) -->\r\n");
      out.write("                        ");
 if (isStaff) { 
      out.write("\r\n");
      out.write("                        <div class=\"section-label\"><i class=\"bi bi-toggle-on me-1\"></i>Update Status\r\n");
      out.write("                            <span class=\"badge bg-warning text-dark fw-normal ms-2\" style=\"font-size:0.7rem;\">Staff Only</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-4\">\r\n");
      out.write("                            <select name=\"status\" class=\"form-select\">\r\n");
      out.write("                                ");
 for (Reservation.Status s : Reservation.Status.values()) { 
      out.write("\r\n");
      out.write("                                <option value=\"");
      out.print( s.name() );
      out.write('"');
      out.write(' ');
      out.print( s == res.getStatus() ? "selected" : "" );
      out.write(">\r\n");
      out.write("                                    ");
      out.print( s.name() );
      out.write("\r\n");
      out.write("                                </option>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <div class=\"form-text text-warning\">\r\n");
      out.write("                                <i class=\"bi bi-exclamation-triangle\"></i>\r\n");
      out.write("                                Changing to CHECKED_OUT or CANCELLED will automatically release the room.\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"d-flex gap-3\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-update flex-grow-1\" id=\"submitBtn\">\r\n");
      out.write("                                <i class=\"bi bi-save me-2\"></i>Save Changes\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=list\"\r\n");
      out.write("                               class=\"btn btn-outline-secondary\">\r\n");
      out.write("                                <i class=\"bi bi-arrow-left me-1\"></i>Back\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                    ");
 } /* end isEditable */ 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- Cancel button shown always (if editable) -->\r\n");
      out.write("                    ");
 if (isEditable) { 
      out.write("\r\n");
      out.write("                    <hr class=\"my-4\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <strong class=\"text-danger\"><i class=\"bi bi-x-octagon me-1\"></i>Cancel Reservation</strong>\r\n");
      out.write("                            <div class=\"text-muted small mt-1\">\r\n");
      out.write("                                Cancellation fee:\r\n");
      out.write("                                <strong>$");
      out.print( String.format("%.2f", res.calculateCancellationFee()) );
      out.write("</strong>\r\n");
      out.write("                                ");
 double fee = res.calculateCancellationFee();
                                   if (fee == 0) { 
      out.write("\r\n");
      out.write("                                <span class=\"badge bg-success ms-1\">Free cancellation</span>\r\n");
      out.write("                                ");
 } else if (fee < res.getTotalAmount()) { 
      out.write("\r\n");
      out.write("                                <span class=\"badge bg-warning text-dark ms-1\">50% fee applies</span>\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                <span class=\"badge bg-danger ms-1\">Full charge applies</span>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations\" method=\"post\"\r\n");
      out.write("                              onsubmit=\"return confirm('Cancel reservation ");
      out.print( resIdStr );
      out.write("?\\n\\nCancellation fee: $");
      out.print( cancelFeeStr );
      out.write("\\n\\nThis cannot be undone.')\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"cancel\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"reservationId\" value=\"");
      out.print( res.getReservationId() );
      out.write("\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-outline-danger\">\r\n");
      out.write("                                <i class=\"bi bi-x-circle me-1\"></i>Cancel Reservation\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h5 style=\"color: #c9a84c;\"><i class=\"bi bi-building\"></i> Grand Vista Hotel</h5>\r\n");
      out.write("                <p class=\"small\">Luxury and comfort, perfectly blended for an unforgettable stay.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h6 class=\"text-white\">Quick Links</h6>\r\n");
      out.write("                <ul class=\"list-unstyled small\">\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/rooms?action=list\">Browse Rooms</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=book\">Make a Reservation</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reviews?action=view\">Guest Reviews</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h6 class=\"text-white\">Contact</h6>\r\n");
      out.write("                <p class=\"small\">\r\n");
      out.write("                    <i class=\"bi bi-geo-alt\"></i> 123 Grand Vista Blvd<br>\r\n");
      out.write("                    <i class=\"bi bi-telephone\"></i> +94 (70) 584-5628<br>\r\n");
      out.write("                    <i class=\"bi bi-envelope\"></i> info@grandvista.com\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr style=\"border-color: rgba(255,255,255,0.2);\">\r\n");
      out.write("        <p class=\"text-center small mb-0\">&copy; 2026 Grand Vista Hotel. All rights reserved | Website Design by SLIIT-KdyUni-G54-2026-SEM-2 (FOC)</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    var currentTotal  = ");
      out.print( res.getTotalAmount() );
      out.write(";\r\n");
      out.write("    var currentNights = ");
      out.print( nights > 0 ? nights : 1 );
      out.write(";\r\n");
      out.write("    var ratePerNight  = currentTotal / currentNights;\r\n");
      out.write("\r\n");
      out.write("    // Today at midnight for accurate comparison\r\n");
      out.write("    var today = new Date();\r\n");
      out.write("    today.setHours(0, 0, 0, 0);\r\n");
      out.write("\r\n");
      out.write("    function toDate(str) {\r\n");
      out.write("        return str ? new Date(str + 'T00:00:00') : null;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function showError(elId, msg) {\r\n");
      out.write("        var el = document.getElementById(elId);\r\n");
      out.write("        el.textContent = msg;\r\n");
      out.write("        el.style.display = msg ? 'block' : 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function onCheckInChange() {\r\n");
      out.write("        var ci = document.getElementById('checkIn').value;\r\n");
      out.write("        showError('checkInError', '');\r\n");
      out.write("\r\n");
      out.write("        if (ci) {\r\n");
      out.write("            var ciDate = toDate(ci);\r\n");
      out.write("\r\n");
      out.write("            // Client-side: check-in cannot be in the past\r\n");
      out.write("            if (ciDate < today) {\r\n");
      out.write("                showError('checkInError', 'Check-in date cannot be in the past.');\r\n");
      out.write("                document.getElementById('checkIn').value = '';\r\n");
      out.write("                document.getElementById('newTotalDiv').style.display = 'none';\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Keep checkOut min always = checkIn + 1 day\r\n");
      out.write("            var nextDay = new Date(ciDate.getTime() + 86400000).toISOString().split('T')[0];\r\n");
      out.write("            document.getElementById('checkOut').min = nextDay;\r\n");
      out.write("\r\n");
      out.write("            // If existing checkOut is now invalid (on or before new checkIn), clear it\r\n");
      out.write("            var co = document.getElementById('checkOut').value;\r\n");
      out.write("            if (co && co <= ci) {\r\n");
      out.write("                document.getElementById('checkOut').value = '';\r\n");
      out.write("                showError('checkOutError', 'Check-out date must be after check-in date.');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        calcNewTotal();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function calcNewTotal() {\r\n");
      out.write("        var ci  = document.getElementById('checkIn').value;\r\n");
      out.write("        var co  = document.getElementById('checkOut').value;\r\n");
      out.write("        var div = document.getElementById('newTotalDiv');\r\n");
      out.write("        var val = document.getElementById('newTotalVal');\r\n");
      out.write("        showError('checkOutError', '');\r\n");
      out.write("\r\n");
      out.write("        if (ci && co) {\r\n");
      out.write("            var ciDate = toDate(ci);\r\n");
      out.write("            var coDate = toDate(co);\r\n");
      out.write("\r\n");
      out.write("            // Client-side: check-out must be after check-in\r\n");
      out.write("            if (coDate <= ciDate) {\r\n");
      out.write("                showError('checkOutError', 'Check-out date must be after check-in date.');\r\n");
      out.write("                div.style.display = 'none';\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            var n = Math.round((coDate - ciDate) / 86400000);\r\n");
      out.write("            if (n > 0) {\r\n");
      out.write("                val.textContent = '$' + (ratePerNight * n).toFixed(2)\r\n");
      out.write("                    + ' (' + n + ' night' + (n !== 1 ? 's' : '') + ')';\r\n");
      out.write("                div.style.display = 'block';\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        div.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Client-side form submit validation — last line of defence before server\r\n");
      out.write("    document.getElementById('modifyForm').addEventListener('submit', function (e) {\r\n");
      out.write("        var ci = document.getElementById('checkIn').value;\r\n");
      out.write("        var co = document.getElementById('checkOut').value;\r\n");
      out.write("\r\n");
      out.write("        // Only validate if either date field has been touched\r\n");
      out.write("        if (ci || co) {\r\n");
      out.write("            if (!ci || !co) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                alert('Please provide both a check-in and check-out date.');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            var ciDate = toDate(ci);\r\n");
      out.write("            var coDate = toDate(co);\r\n");
      out.write("\r\n");
      out.write("            if (ciDate < today) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                showError('checkInError', 'Check-in date cannot be in the past.');\r\n");
      out.write("                document.getElementById('checkIn').focus();\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (coDate <= ciDate) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                showError('checkOutError', 'Check-out date must be after check-in date.');\r\n");
      out.write("                document.getElementById('checkOut').focus();\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            var nights = Math.round((coDate - ciDate) / 86400000);\r\n");
      out.write("            if (nights > 90) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                alert('Reservations cannot exceed 90 nights.');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    window.addEventListener('DOMContentLoaded', calcNewTotal);\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
