/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2026-05-17 09:47:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hotel.model.*;
import com.hotel.model.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1778867051865L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1778867051865L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.hotel.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    Reservation res = (Reservation) request.getAttribute("reservation");
    if (res == null) { response.sendRedirect(request.getContextPath() + "/reservations?action=list"); return; }
    String guestName = (String) request.getAttribute("guestName");
    Double cancellationFee = (Double) request.getAttribute("cancellationFee");
    if (cancellationFee == null) cancellationFee = 0.0;
    boolean isStaff = session.getAttribute("loggedInStaff") != null;
    long nights = res.getNights();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Reservation Details - Grand Vista Hotel</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .page-header { background: linear-gradient(135deg, var(--hotel-primary), #2d6a9f); color: white; padding: 32px 0 50px; margin-bottom: -24px; }\r\n");
      out.write("        .view-card { border-radius: 14px; border: none; box-shadow: 0 4px 20px rgba(26,60,94,0.12); }\r\n");
      out.write("        .detail-section { padding: 24px; border-bottom: 1px solid #eef2f7; }\r\n");
      out.write("        .detail-section:last-child { border-bottom: none; }\r\n");
      out.write("        .section-heading { font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.7px; font-weight: 700; color: var(--hotel-primary); margin-bottom: 16px; }\r\n");
      out.write("        .detail-row { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; }\r\n");
      out.write("        .detail-label { color: #6c757d; font-size: 0.88rem; }\r\n");
      out.write("        .detail-value { font-weight: 600; font-size: 0.92rem; }\r\n");
      out.write("        .status-badge { display: inline-flex; align-items: center; gap: 5px; padding: 6px 14px; border-radius: 20px; font-weight: 600; font-size: 0.82rem; }\r\n");
      out.write("        .s-PENDING    { background:#fff3cd; color:#856404; }\r\n");
      out.write("        .s-CONFIRMED  { background:#d1e7dd; color:#0f5132; }\r\n");
      out.write("        .s-CHECKED_IN { background:#cff4fc; color:#055160; }\r\n");
      out.write("        .s-CHECKED_OUT{ background:#e2e3e5; color:#383d41; }\r\n");
      out.write("        .s-CANCELLED  { background:#f8d7da; color:#842029; }\r\n");
      out.write("        .total-display { font-size: 2rem; font-weight: 800; color: #1a6b3c; }\r\n");
      out.write("        .timeline { position: relative; padding-left: 28px; }\r\n");
      out.write("        .timeline::before { content:''; position: absolute; left: 7px; top: 0; bottom: 0; width: 2px; background: #e0e8f0; }\r\n");
      out.write("        .tl-item { position: relative; margin-bottom: 16px; }\r\n");
      out.write("        .tl-dot { position: absolute; left: -28px; top: 2px; width: 16px; height: 16px; border-radius: 50%; border: 2px solid; background: white; }\r\n");
      out.write("        .tl-dot.done   { border-color: #198754; background: #198754; }\r\n");
      out.write("        .tl-dot.active { border-color: var(--hotel-primary); background: var(--hotel-primary); }\r\n");
      out.write("        .tl-dot.future { border-color: #ced4da; }\r\n");
      out.write("        .tl-label { font-weight: 600; font-size: 0.85rem; }\r\n");
      out.write("        .tl-date  { font-size: 0.78rem; color: #6c757d; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Guest loggedInGuest = (Guest) session.getAttribute("loggedInGuest");
    Staff loggedInStaff = (Staff) session.getAttribute("loggedInStaff");
    String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-hotel navbar-dark\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print( contextPath );
      out.write("/index.jsp\">\r\n");
      out.write("            <i class=\"bi bi-building\"></i> Grand Vista Hotel\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarMain\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarMain\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=list\">\r\n");
      out.write("                        <i class=\"bi bi-door-open\"></i> Rooms\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=book\">\r\n");
      out.write("                        <i class=\"bi bi-calendar-plus\"></i> Book Now\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=view\">\r\n");
      out.write("                        <i class=\"bi bi-star\"></i> Reviews\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-gear\"></i> Management\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=dashboard\">Dashboard</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=list\">Guests</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">Payments</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=moderate\">Moderate Reviews</a></li>\r\n");
      out.write("                        ");
 if (loggedInStaff instanceof Manager) { 
      out.write("\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=add\">Add Room</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=manage\">Manage Staff</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                ");
 if (loggedInGuest != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-circle\"></i> ");
      out.print( loggedInGuest.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=profile\">My Profile</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">My Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">My Payments</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-badge\"></i> ");
      out.print( loggedInStaff.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><span class=\"dropdown-item-text text-muted small\">");
      out.print( loggedInStaff.getRole() );
      out.write("</span></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-box-arrow-in-right\"></i> Guest Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-shield-lock\"></i> Staff Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("            <ol class=\"breadcrumb mb-1\" style=\"--bs-breadcrumb-divider-color:rgba(255,255,255,0.4);\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"text-white-50\">Home</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=list\" class=\"text-white-50\">Reservations</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active text-white\">Details</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"d-flex align-items-center gap-3\">\r\n");
      out.write("            <h3 class=\"fw-bold mb-0\"><i class=\"bi bi-file-earmark-text me-2\"></i>Reservation Details</h3>\r\n");
      out.write("            <span class=\"status-badge s-");
      out.print( res.getStatus().name() );
      out.write("\">\r\n");
      out.write("                <i class=\"bi bi-circle-fill\" style=\"font-size:0.5rem;\"></i>\r\n");
      out.write("                ");
      out.print( res.getStatus() );
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mt-1 opacity-75\" style=\"font-family:monospace; font-size:0.85rem;\">\r\n");
      out.write("            #");
      out.print( res.getReservationId() );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-5\">\r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("        <!-- Main Details -->\r\n");
      out.write("        <div class=\"col-lg-8\">\r\n");
      out.write("            <div class=\"card view-card\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Guest & Room -->\r\n");
      out.write("                <div class=\"detail-section\">\r\n");
      out.write("                    <div class=\"section-heading\"><i class=\"bi bi-person me-1\"></i>Guest & Room</div>\r\n");
      out.write("                    <div class=\"row g-3\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"detail-row\">\r\n");
      out.write("                                <span class=\"detail-label\">Guest Name</span>\r\n");
      out.write("                                <span class=\"detail-value\">");
      out.print( guestName );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"detail-row\">\r\n");
      out.write("                                <span class=\"detail-label\">Guest ID</span>\r\n");
      out.write("                                <code class=\"text-secondary\">");
      out.print( res.getGuestId() );
      out.write("</code>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"detail-row\">\r\n");
      out.write("                                <span class=\"detail-label\">Room Number</span>\r\n");
      out.write("                                <span class=\"detail-value\">Room ");
      out.print( res.getRoomNumber() );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 if (!res.getCreatedAt().isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"detail-row\">\r\n");
      out.write("                                <span class=\"detail-label\">Booked On</span>\r\n");
      out.write("                                <span class=\"detail-value\">");
      out.print( res.getCreatedAt() );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Stay Dates -->\r\n");
      out.write("                <div class=\"detail-section\">\r\n");
      out.write("                    <div class=\"section-heading\"><i class=\"bi bi-calendar-range me-1\"></i>Stay Details</div>\r\n");
      out.write("                    <div class=\"row g-3\">\r\n");
      out.write("                        <div class=\"col-md-4 text-center\">\r\n");
      out.write("                            <div class=\"border rounded p-3\">\r\n");
      out.write("                                <div style=\"font-size:0.72rem; text-transform:uppercase; color:#6c757d; letter-spacing:0.5px;\">Check-In</div>\r\n");
      out.write("                                <div class=\"fw-bold mt-1\">");
      out.print( res.getCheckIn() != null ? res.getCheckIn() : "—" );
      out.write("</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4 text-center d-flex align-items-center justify-content-center\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div class=\"fw-bold\" style=\"font-size:1.4rem; color:var(--hotel-primary);\">");
      out.print( nights );
      out.write("</div>\r\n");
      out.write("                                <div style=\"font-size:0.78rem; color:#6c757d;\">night");
      out.print( nights != 1 ? "s" : "" );
      out.write("</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4 text-center\">\r\n");
      out.write("                            <div class=\"border rounded p-3\">\r\n");
      out.write("                                <div style=\"font-size:0.72rem; text-transform:uppercase; color:#6c757d; letter-spacing:0.5px;\">Check-Out</div>\r\n");
      out.write("                                <div class=\"fw-bold mt-1\">");
      out.print( res.getCheckOut() != null ? res.getCheckOut() : "—" );
      out.write("</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Special Requests -->\r\n");
      out.write("                ");
 if (res.getSpecialRequests() != null && !res.getSpecialRequests().isEmpty()) { 
      out.write("\r\n");
      out.write("                <div class=\"detail-section\">\r\n");
      out.write("                    <div class=\"section-heading\"><i class=\"bi bi-chat-square-text me-1\"></i>Special Requests</div>\r\n");
      out.write("                    <p class=\"text-muted mb-0\">");
      out.print( res.getSpecialRequests() );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Cancellation Policy -->\r\n");
      out.write("                <div class=\"detail-section\">\r\n");
      out.write("                    <div class=\"section-heading\"><i class=\"bi bi-shield-exclamation me-1\"></i>Cancellation Policy</div>\r\n");
      out.write("                    <div class=\"detail-row\">\r\n");
      out.write("                        <span class=\"detail-label\">Cancellation Fee (if cancelled now)</span>\r\n");
      out.write("                        <span class=\"detail-value\">\r\n");
      out.write("                            $");
      out.print( String.format("%.2f", cancellationFee) );
      out.write("\r\n");
      out.write("                            ");
 if (cancellationFee == 0) { 
      out.write("<span class=\"badge bg-success ms-1\">Free</span>\r\n");
      out.write("                            ");
 } else if (cancellationFee < res.getTotalAmount()) { 
      out.write("<span class=\"badge bg-warning text-dark ms-1\">50%</span>\r\n");
      out.write("                            ");
 } else { 
      out.write("<span class=\"badge bg-danger ms-1\">Full charge</span>");
 } 
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar -->\r\n");
      out.write("        <div class=\"col-lg-4\">\r\n");
      out.write("            <!-- Total -->\r\n");
      out.write("            <div class=\"card view-card mb-3\">\r\n");
      out.write("                <div class=\"card-body p-4 text-center\">\r\n");
      out.write("                    <div style=\"font-size:0.75rem; text-transform:uppercase; letter-spacing:0.5px; color:#6c757d;\">Total Amount</div>\r\n");
      out.write("                    <div class=\"total-display my-2\">$");
      out.print( String.format("%.2f", res.getTotalAmount()) );
      out.write("</div>\r\n");
      out.write("                    <div class=\"text-muted small\">");
      out.print( nights );
      out.write(" night");
      out.print( nights!=1?"s":"" );
      out.write(" &bull; Room ");
      out.print( res.getRoomNumber() );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Status Timeline -->\r\n");
      out.write("            <div class=\"card view-card mb-3\">\r\n");
      out.write("                <div class=\"card-body p-4\">\r\n");
      out.write("                    <div class=\"section-heading\"><i class=\"bi bi-arrow-right-circle me-1\"></i>Status Progress</div>\r\n");
      out.write("                    <div class=\"timeline\">\r\n");
      out.write("                        ");

                            Reservation.Status[] statuses = {
                                Reservation.Status.PENDING,
                                Reservation.Status.CONFIRMED,
                                Reservation.Status.CHECKED_IN,
                                Reservation.Status.CHECKED_OUT
                            };
                            int curIdx = 0;
                            for (int i = 0; i < statuses.length; i++) {
                                if (statuses[i] == res.getStatus()) { curIdx = i; break; }
                            }
                            if (res.getStatus() == Reservation.Status.CANCELLED) { curIdx = -1; }
                        
      out.write("\r\n");
      out.write("                        ");
 if (res.getStatus() == Reservation.Status.CANCELLED) { 
      out.write("\r\n");
      out.write("                        <div class=\"tl-item\">\r\n");
      out.write("                            <div class=\"tl-dot\" style=\"border-color:#dc3545; background:#dc3545;\"></div>\r\n");
      out.write("                            <div class=\"tl-label text-danger\">CANCELLED</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 } else {
                            for (int i = 0; i < statuses.length; i++) { 
      out.write("\r\n");
      out.write("                        <div class=\"tl-item\">\r\n");
      out.write("                            <div class=\"tl-dot ");
      out.print( i < curIdx ? "done" : (i == curIdx ? "active" : "future") );
      out.write("\"></div>\r\n");
      out.write("                            <div class=\"tl-label ");
      out.print( i == curIdx ? "text-primary" : (i < curIdx ? "text-success" : "text-muted") );
      out.write("\">\r\n");
      out.write("                                ");
      out.print( statuses[i].name() );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 } } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Actions -->\r\n");
      out.write("            <div class=\"card view-card\">\r\n");
      out.write("                <div class=\"card-body p-3\">\r\n");
      out.write("                    <div class=\"d-grid gap-2\">\r\n");
      out.write("                        ");
 if (res.getStatus() != Reservation.Status.CANCELLED && res.getStatus() != Reservation.Status.CHECKED_OUT) { 
      out.write("\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=modify&reservationId=");
      out.print( res.getReservationId() );
      out.write("\"\r\n");
      out.write("                           class=\"btn btn-hotel-primary\">\r\n");
      out.write("                            <i class=\"bi bi-pencil me-1\"></i>Modify Reservation\r\n");
      out.write("                        </a>\r\n");
      out.write("                        ");
 if (res.getStatus() != Reservation.Status.CHECKED_IN) { 
      out.write("\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/payments?action=checkout&reservationId=");
      out.print( res.getReservationId() );
      out.write("\"\r\n");
      out.write("                           class=\"btn btn-success\">\r\n");
      out.write("                            <i class=\"bi bi-credit-card me-1\"></i>Make Payment\r\n");
      out.write("                        </a>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=list\"\r\n");
      out.write("                           class=\"btn btn-outline-secondary\">\r\n");
      out.write("                            <i class=\"bi bi-arrow-left me-1\"></i>Back to List\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h5 style=\"color: #c9a84c;\"><i class=\"bi bi-building\"></i> Grand Vista Hotel</h5>\r\n");
      out.write("                <p class=\"small\">Luxury and comfort, perfectly blended for an unforgettable stay.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h6 class=\"text-white\">Quick Links</h6>\r\n");
      out.write("                <ul class=\"list-unstyled small\">\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/rooms?action=list\">Browse Rooms</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=book\">Make a Reservation</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reviews?action=view\">Guest Reviews</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h6 class=\"text-white\">Contact</h6>\r\n");
      out.write("                <p class=\"small\">\r\n");
      out.write("                    <i class=\"bi bi-geo-alt\"></i> 123 Grand Vista Blvd<br>\r\n");
      out.write("                    <i class=\"bi bi-telephone\"></i> +94 (70) 584-5628<br>\r\n");
      out.write("                    <i class=\"bi bi-envelope\"></i> info@grandvista.com\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr style=\"border-color: rgba(255,255,255,0.2);\">\r\n");
      out.write("        <p class=\"text-center small mb-0\">&copy; 2026 Grand Vista Hotel. All rights reserved | Website Design by SLIIT-KdyUni-G54-2026-SEM-2 (FOC)</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
