/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2026-03-11 09:25:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hotel.model.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1772014307412L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1773221092899L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.hotel.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Grand Vista Hotel</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Guest loggedInGuest = (Guest) session.getAttribute("loggedInGuest");
    Staff loggedInStaff = (Staff) session.getAttribute("loggedInStaff");
    String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-hotel navbar-dark\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print( contextPath );
      out.write("/index.jsp\">\r\n");
      out.write("            <i class=\"bi bi-building\"></i> Grand Vista Hotel\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarMain\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarMain\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=list\">\r\n");
      out.write("                        <i class=\"bi bi-door-open\"></i> Rooms\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=book\">\r\n");
      out.write("                        <i class=\"bi bi-calendar-plus\"></i> Book Now\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=view\">\r\n");
      out.write("                        <i class=\"bi bi-star\"></i> Reviews\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-gear\"></i> Management\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=dashboard\">Dashboard</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=list\">Guests</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">Payments</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=moderate\">Moderate Reviews</a></li>\r\n");
      out.write("                        ");
 if (loggedInStaff instanceof Manager) { 
      out.write("\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=add\">Add Room</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=manage\">Manage Staff</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                ");
 if (loggedInGuest != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-circle\"></i> ");
      out.print( loggedInGuest.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=profile\">My Profile</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">My Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">My Payments</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-badge\"></i> ");
      out.print( loggedInStaff.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><span class=\"dropdown-item-text text-muted small\">");
      out.print( loggedInStaff.getRole() );
      out.write("</span></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-box-arrow-in-right\"></i> Guest Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-shield-lock\"></i> Staff Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Hero Section -->\r\n");
      out.write("<section class=\"hero-section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-lg-8\">\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <i class=\"bi bi-building\" style=\"font-size:4rem; color: #c9a84c;\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1>Welcome to Grand Vista Hotel</h1>\r\n");
      out.write("                <p class=\"lead\">Experience luxury, comfort, and world-class hospitality.</p>\r\n");
      out.write("                <div class=\"mt-4\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=book\"\r\n");
      out.write("                       class=\"btn btn-hotel-gold btn-lg me-3\">\r\n");
      out.write("                        <i class=\"bi bi-calendar-plus\"></i> Book a Room\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/rooms?action=list\"\r\n");
      out.write("                       class=\"btn btn-outline-light btn-lg\">\r\n");
      out.write("                        <i class=\"bi bi-door-open\"></i> View Rooms\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Quick Links -->\r\n");
      out.write("<section class=\"py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 class=\"text-center mb-4\" style=\"color: var(--hotel-primary);\">Our Services</h2>\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card h-100 text-center p-3\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <i class=\"bi bi-door-open\" style=\"font-size:2.5rem; color: var(--hotel-primary);\"></i>\r\n");
      out.write("                        <h5 class=\"mt-3\">Browse Rooms</h5>\r\n");
      out.write("                        <p class=\"text-muted small\">Explore our Standard and Suite rooms</p>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/rooms?action=list\"\r\n");
      out.write("                           class=\"btn btn-hotel-primary btn-sm\">View Rooms</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card h-100 text-center p-3\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <i class=\"bi bi-calendar-check\" style=\"font-size:2.5rem; color: #28a745;\"></i>\r\n");
      out.write("                        <h5 class=\"mt-3\">Make a Reservation</h5>\r\n");
      out.write("                        <p class=\"text-muted small\">Book your stay in minutes</p>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=book\"\r\n");
      out.write("                           class=\"btn btn-success btn-sm\">Book Now</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card h-100 text-center p-3\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <i class=\"bi bi-person-plus\" style=\"font-size:2.5rem; color: #17a2b8;\"></i>\r\n");
      out.write("                        <h5 class=\"mt-3\">Guest Login</h5>\r\n");
      out.write("                        <p class=\"text-muted small\">Manage your reservations & profile</p>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/guests?action=login\"\r\n");
      out.write("                           class=\"btn btn-info btn-sm text-white\">Login</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card h-100 text-center p-3\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <i class=\"bi bi-shield-lock\" style=\"font-size:2.5rem; color: var(--hotel-secondary);\"></i>\r\n");
      out.write("                        <h5 class=\"mt-3\">Staff Portal</h5>\r\n");
      out.write("                        <p class=\"text-muted small\">Hotel management dashboard</p>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/staff?action=login\"\r\n");
      out.write("                           class=\"btn btn-warning btn-sm\">Staff Login</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Reviews Preview -->\r\n");
      out.write("<section class=\"py-5 bg-white\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 class=\"text-center mb-4\" style=\"color: var(--hotel-primary);\">What Our Guests Say</h2>\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-3\">\r\n");
      out.write("                    <div class=\"stars\">&#9733;&#9733;&#9733;&#9733;&#9733;</div>\r\n");
      out.write("                    <p class=\"mt-2 text-muted\">\"An absolutely wonderful experience. The rooms were immaculate and the staff were incredibly helpful!\"</p>\r\n");
      out.write("                    <small class=\"text-muted\">— John D., Verified Guest</small>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-3\">\r\n");
      out.write("                    <div class=\"stars\">&#9733;&#9733;&#9733;&#9733;&#9733;</div>\r\n");
      out.write("                    <p class=\"mt-2 text-muted\">\"The suite was breathtaking. Jacuzzi, amazing views, and the breakfast was superb.\"</p>\r\n");
      out.write("                    <small class=\"text-muted\">— Sarah M., Verified Guest</small>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-3\">\r\n");
      out.write("                    <div class=\"stars\">&#9733;&#9733;&#9733;&#9733;&#9734;</div>\r\n");
      out.write("                    <p class=\"mt-2 text-muted\">\"Great value for money. Clean, comfortable and perfectly located.\"</p>\r\n");
      out.write("                    <small class=\"text-muted\">— TravelLover42, Guest</small>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"text-center mt-4\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reviews?action=view\" class=\"btn btn-hotel-primary\">\r\n");
      out.write("                <i class=\"bi bi-star\"></i> Read All Reviews\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
