/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2026-05-15 18:11:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hotel.model.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1778867051865L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1778867051865L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.hotel.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Grand Vista Hotel</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap & Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Animate.css for entrance animations -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Hero Section with Animated Gradient & Rain/Snow Effect */\r\n");
      out.write("        .hero-section {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            background: linear-gradient(-45deg, #1a3c5e, #2d6a9f, #0f2027, #203a43);\r\n");
      out.write("            background-size: 400% 400%;\r\n");
      out.write("            animation: gradientBG 15s ease infinite;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 120px 0 140px 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            border-bottom: 5px solid var(--hotel-secondary);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes gradientBG {\r\n");
      out.write("            0% { background-position: 0% 50%; }\r\n");
      out.write("            50% { background-position: 100% 50%; }\r\n");
      out.write("            100% { background-position: 0% 50%; }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* ------------------------------------\r\n");
      out.write("           Falling Rain / Snow (පොද වැටෙන Animation)\r\n");
      out.write("           ------------------------------------ */\r\n");
      out.write("        .rain-container {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .drop {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.4);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            /* පොඩි තිත් වගේ පේන්න */\r\n");
      out.write("            width: 3px;\r\n");
      out.write("            height: 3px;\r\n");
      out.write("            box-shadow: 0 0 5px rgba(255,255,255,0.8);\r\n");
      out.write("            animation: fall linear infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fall {\r\n");
      out.write("            0% {\r\n");
      out.write("                transform: translateY(-20px) translateX(0);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("            10% { opacity: 1; }\r\n");
      out.write("            90% { opacity: 1; }\r\n");
      out.write("            100% {\r\n");
      out.write("                transform: translateY(100vh) translateX(20px); /* වැටෙද්දී පොඩ්ඩක් ඇලවෙනවා */\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Generating Multiple Drops using CSS nth-child */\r\n");
      out.write("        .drop:nth-child(1) { left: 10%; animation-duration: 4s; animation-delay: 0s; width: 4px; height: 4px; }\r\n");
      out.write("        .drop:nth-child(2) { left: 20%; animation-duration: 3s; animation-delay: 1s; }\r\n");
      out.write("        .drop:nth-child(3) { left: 30%; animation-duration: 5s; animation-delay: 2s; width: 2px; height: 2px; }\r\n");
      out.write("        .drop:nth-child(4) { left: 40%; animation-duration: 4.5s; animation-delay: 0.5s; }\r\n");
      out.write("        .drop:nth-child(5) { left: 50%; animation-duration: 3.5s; animation-delay: 1.5s; width: 5px; height: 5px; }\r\n");
      out.write("        .drop:nth-child(6) { left: 60%; animation-duration: 6s; animation-delay: 0.2s; }\r\n");
      out.write("        .drop:nth-child(7) { left: 70%; animation-duration: 4s; animation-delay: 2s; width: 3px; height: 3px; }\r\n");
      out.write("        .drop:nth-child(8) { left: 80%; animation-duration: 3.8s; animation-delay: 1.2s; }\r\n");
      out.write("        .drop:nth-child(9) { left: 90%; animation-duration: 5s; animation-delay: 0.8s; }\r\n");
      out.write("        .drop:nth-child(10) { left: 15%; animation-duration: 4.2s; animation-delay: 1.8s; width: 4px; height: 4px;}\r\n");
      out.write("        .drop:nth-child(11) { left: 35%; animation-duration: 3.2s; animation-delay: 0.3s; }\r\n");
      out.write("        .drop:nth-child(12) { left: 55%; animation-duration: 5.5s; animation-delay: 2.5s; }\r\n");
      out.write("        .drop:nth-child(13) { left: 75%; animation-duration: 4.8s; animation-delay: 0.6s; width: 2px; height: 2px;}\r\n");
      out.write("        .drop:nth-child(14) { left: 85%; animation-duration: 3.7s; animation-delay: 1.1s; }\r\n");
      out.write("        .drop:nth-child(15) { left: 95%; animation-duration: 4.1s; animation-delay: 1.9s; }\r\n");
      out.write("        .drop:nth-child(16) { left: 5%; animation-duration: 5.2s; animation-delay: 0.7s; }\r\n");
      out.write("        .drop:nth-child(17) { left: 25%; animation-duration: 3.9s; animation-delay: 1.4s; width: 5px; height: 5px;}\r\n");
      out.write("        .drop:nth-child(18) { left: 45%; animation-duration: 4.6s; animation-delay: 0.9s; }\r\n");
      out.write("        .drop:nth-child(19) { left: 65%; animation-duration: 3.4s; animation-delay: 2.1s; }\r\n");
      out.write("        .drop:nth-child(20) { left: 98%; animation-duration: 5.8s; animation-delay: 0.4s; width: 3px; height: 3px;}\r\n");
      out.write("\r\n");
      out.write("        /* Hero Content Styling */\r\n");
      out.write("        .hero-content {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-section h1 {\r\n");
      out.write("            font-size: 3.8rem;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            text-shadow: 2px 4px 8px rgba(0,0,0,0.5);\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-section p.lead {\r\n");
      out.write("            font-size: 1.4rem;\r\n");
      out.write("            text-shadow: 1px 2px 4px rgba(0,0,0,0.4);\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hotel-icon-main {\r\n");
      out.write("            font-size: 5rem;\r\n");
      out.write("            background: -webkit-linear-gradient(45deg, #c9a84c, #f4c430);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            filter: drop-shadow(0px 5px 15px rgba(0,0,0,0.4));\r\n");
      out.write("            animation: pulse 2s infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hover Effects for Cards below */\r\n");
      out.write("        .service-card {\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            border: none;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0,0,0,0.08);\r\n");
      out.write("            border-bottom: 4px solid transparent;\r\n");
      out.write("        }\r\n");
      out.write("        .service-card:hover {\r\n");
      out.write("            transform: translateY(-10px);\r\n");
      out.write("            box-shadow: 0 15px 30px rgba(0,0,0,0.15);\r\n");
      out.write("            border-bottom: 4px solid var(--hotel-secondary);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Guest loggedInGuest = (Guest) session.getAttribute("loggedInGuest");
    Staff loggedInStaff = (Staff) session.getAttribute("loggedInStaff");
    String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-hotel navbar-dark\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print( contextPath );
      out.write("/index.jsp\">\r\n");
      out.write("            <i class=\"bi bi-building\"></i> Grand Vista Hotel\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarMain\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarMain\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=list\">\r\n");
      out.write("                        <i class=\"bi bi-door-open\"></i> Rooms\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=book\">\r\n");
      out.write("                        <i class=\"bi bi-calendar-plus\"></i> Book Now\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=view\">\r\n");
      out.write("                        <i class=\"bi bi-star\"></i> Reviews\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-gear\"></i> Management\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=dashboard\">Dashboard</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=list\">Guests</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">Payments</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reviews?action=moderate\">Moderate Reviews</a></li>\r\n");
      out.write("                        ");
 if (loggedInStaff instanceof Manager) { 
      out.write("\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/rooms?action=add\">Add Room</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=manage\">Manage Staff</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                ");
 if (loggedInGuest != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-circle\"></i> ");
      out.print( loggedInGuest.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=profile\">My Profile</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/reservations?action=list\">My Reservations</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print( contextPath );
      out.write("/payments?action=history\">My Payments</a></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else if (loggedInStaff != null) { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <i class=\"bi bi-person-badge\"></i> ");
      out.print( loggedInStaff.getName() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end\">\r\n");
      out.write("                        <li><span class=\"dropdown-item-text text-muted small\">");
      out.print( loggedInStaff.getRole() );
      out.write("</span></li>\r\n");
      out.write("                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-danger\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=logout\">Logout</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/guests?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-box-arrow-in-right\"></i> Guest Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( contextPath );
      out.write("/staff?action=login\">\r\n");
      out.write("                        <i class=\"bi bi-shield-lock\"></i> Staff Login\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Hero Section -->\r\n");
      out.write("<section class=\"hero-section\">\r\n");
      out.write("    <!-- Rain / Falling Snow Animation Container -->\r\n");
      out.write("    <div class=\"rain-container\">\r\n");
      out.write("        <div class=\"drop\"></div><div class=\"drop\"></div><div class=\"drop\"></div><div class=\"drop\"></div>\r\n");
      out.write("        <div class=\"drop\"></div><div class=\"drop\"></div><div class=\"drop\"></div><div class=\"drop\"></div>\r\n");
      out.write("        <div class=\"drop\"></div><div class=\"drop\"></div><div class=\"drop\"></div><div class=\"drop\"></div>\r\n");
      out.write("        <div class=\"drop\"></div><div class=\"drop\"></div><div class=\"drop\"></div><div class=\"drop\"></div>\r\n");
      out.write("        <div class=\"drop\"></div><div class=\"drop\"></div><div class=\"drop\"></div><div class=\"drop\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container hero-content\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-lg-9\">\r\n");
      out.write("                <div class=\"mb-3 animate__animated animate__fadeInDown\">\r\n");
      out.write("                    <i class=\"bi bi-building hotel-icon-main\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1 class=\"animate__animated animate__zoomIn\" style=\"animation-delay: 0.3s;\">\r\n");
      out.write("                    Welcome to Grand Vista Hotel\r\n");
      out.write("                </h1>\r\n");
      out.write("                <p class=\"lead animate__animated animate__fadeInUp\" style=\"animation-delay: 0.6s;\">\r\n");
      out.write("                    Experience luxury, comfort, and world-class hospitality.\r\n");
      out.write("                </p>\r\n");
      out.write("                <div class=\"mt-4 animate__animated animate__fadeInUp\" style=\"animation-delay: 0.9s;\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=book\"\r\n");
      out.write("                       class=\"btn btn-hotel-gold btn-lg me-3 px-4 py-3 shadow-lg rounded-pill\" style=\"transition: 0.3s;\">\r\n");
      out.write("                        <i class=\"bi bi-calendar-plus-fill me-2\"></i> Book a Room\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/rooms?action=list\"\r\n");
      out.write("                       class=\"btn btn-outline-light btn-lg px-4 py-3 rounded-pill\" style=\"transition: 0.3s;\">\r\n");
      out.write("                        <i class=\"bi bi-door-open-fill me-2\"></i> View Rooms\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Quick Links -->\r\n");
      out.write("<section class=\"py-5\" style=\"background-color: #f8f9fa;\">\r\n");
      out.write("    <div class=\"container mt-n5 position-relative\" style=\"z-index: 20; transform: translateY(-60px);\">\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card service-card h-100 text-center p-4 rounded-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"mb-3 p-3 bg-primary bg-opacity-10 rounded-circle d-inline-block\">\r\n");
      out.write("                            <i class=\"bi bi-door-open\" style=\"font-size:2.5rem; color: var(--hotel-primary);\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h5 class=\"fw-bold\">Browse Rooms</h5>\r\n");
      out.write("                        <p class=\"text-muted small\">Explore our Standard and Suite rooms</p>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/rooms?action=list\"\r\n");
      out.write("                           class=\"btn btn-outline-primary btn-sm rounded-pill px-3\">View Rooms</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card service-card h-100 text-center p-4 rounded-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"mb-3 p-3 bg-success bg-opacity-10 rounded-circle d-inline-block\">\r\n");
      out.write("                            <i class=\"bi bi-calendar-check\" style=\"font-size:2.5rem; color: #28a745;\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h5 class=\"fw-bold\">Make a Reservation</h5>\r\n");
      out.write("                        <p class=\"text-muted small\">Book your stay in minutes</p>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=book\"\r\n");
      out.write("                           class=\"btn btn-outline-success btn-sm rounded-pill px-3\">Book Now</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card service-card h-100 text-center p-4 rounded-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"mb-3 p-3 bg-info bg-opacity-10 rounded-circle d-inline-block\">\r\n");
      out.write("                            <i class=\"bi bi-person-plus\" style=\"font-size:2.5rem; color: #17a2b8;\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h5 class=\"fw-bold\">Guest Login</h5>\r\n");
      out.write("                        <p class=\"text-muted small\">Manage your reservations & profile</p>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/guests?action=login\"\r\n");
      out.write("                           class=\"btn btn-outline-info btn-sm rounded-pill px-3\">Login</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card service-card h-100 text-center p-4 rounded-4\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"mb-3 p-3 bg-warning bg-opacity-10 rounded-circle d-inline-block\">\r\n");
      out.write("                            <i class=\"bi bi-shield-lock\" style=\"font-size:2.5rem; color: var(--hotel-secondary);\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h5 class=\"fw-bold\">Staff Portal</h5>\r\n");
      out.write("                        <p class=\"text-muted small\">Hotel management dashboard</p>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/staff?action=login\"\r\n");
      out.write("                           class=\"btn btn-outline-warning btn-sm rounded-pill px-3\">Staff Login</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Reviews Preview -->\r\n");
      out.write("<section class=\"py-5 bg-white mb-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"text-center mb-5\">\r\n");
      out.write("            <h2 class=\"fw-bold\" style=\"color: var(--hotel-primary);\">What Our Guests Say</h2>\r\n");
      out.write("            <div style=\"width: 60px; height: 3px; background: var(--hotel-secondary); margin: 0 auto;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row justify-content-center g-4\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-4 service-card rounded-4 border-0 bg-light\">\r\n");
      out.write("                    <div class=\"stars mb-3 text-warning fs-4\">&#9733;&#9733;&#9733;&#9733;&#9733;</div>\r\n");
      out.write("                    <p class=\"fst-italic text-secondary\">\"An absolutely wonderful experience. The rooms were immaculate and the staff were incredibly helpful!\"</p>\r\n");
      out.write("                    <div class=\"mt-3 d-flex align-items-center\">\r\n");
      out.write("                        <div class=\"bg-primary text-white rounded-circle d-flex justify-content-center align-items-center me-3\" style=\"width: 40px; height: 40px; fw-bold\">J</div>\r\n");
      out.write("                        <small class=\"fw-bold\">— John D.<br><span class=\"text-success fw-normal\"><i class=\"bi bi-check-circle-fill\"></i> Verified Guest</span></small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-4 service-card rounded-4 border-0 bg-light\">\r\n");
      out.write("                    <div class=\"stars mb-3 text-warning fs-4\">&#9733;&#9733;&#9733;&#9733;&#9733;</div>\r\n");
      out.write("                    <p class=\"fst-italic text-secondary\">\"The suite was breathtaking. Jacuzzi, amazing views, and the breakfast was superb.\"</p>\r\n");
      out.write("                    <div class=\"mt-3 d-flex align-items-center\">\r\n");
      out.write("                        <div class=\"bg-success text-white rounded-circle d-flex justify-content-center align-items-center me-3\" style=\"width: 40px; height: 40px; fw-bold\">S</div>\r\n");
      out.write("                        <small class=\"fw-bold\">— Sarah M.<br><span class=\"text-success fw-normal\"><i class=\"bi bi-check-circle-fill\"></i> Verified Guest</span></small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-4 service-card rounded-4 border-0 bg-light\">\r\n");
      out.write("                    <div class=\"stars mb-3 text-warning fs-4\">&#9733;&#9733;&#9733;&#9733;&#9734;</div>\r\n");
      out.write("                    <p class=\"fst-italic text-secondary\">\"Great value for money. Clean, comfortable and perfectly located. Highly recommended!\"</p>\r\n");
      out.write("                    <div class=\"mt-3 d-flex align-items-center\">\r\n");
      out.write("                        <div class=\"bg-secondary text-white rounded-circle d-flex justify-content-center align-items-center me-3\" style=\"width: 40px; height: 40px; fw-bold\">T</div>\r\n");
      out.write("                        <small class=\"fw-bold\">— TravelLover42<br><span class=\"text-muted fw-normal\">Guest</span></small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"text-center mt-5\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reviews?action=view\" class=\"btn btn-outline-primary rounded-pill px-4 py-2\">\r\n");
      out.write("                <i class=\"bi bi-star-fill me-2\"></i> Read All Reviews\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h5 style=\"color: #c9a84c;\"><i class=\"bi bi-building\"></i> Grand Vista Hotel</h5>\r\n");
      out.write("                <p class=\"small\">Luxury and comfort, perfectly blended for an unforgettable stay.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h6 class=\"text-white\">Quick Links</h6>\r\n");
      out.write("                <ul class=\"list-unstyled small\">\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/rooms?action=list\">Browse Rooms</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reservations?action=book\">Make a Reservation</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reviews?action=view\">Guest Reviews</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <h6 class=\"text-white\">Contact</h6>\r\n");
      out.write("                <p class=\"small\">\r\n");
      out.write("                    <i class=\"bi bi-geo-alt\"></i> 123 Grand Vista Blvd<br>\r\n");
      out.write("                    <i class=\"bi bi-telephone\"></i> +94 (70) 584-5628<br>\r\n");
      out.write("                    <i class=\"bi bi-envelope\"></i> info@grandvista.com\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr style=\"border-color: rgba(255,255,255,0.2);\">\r\n");
      out.write("        <p class=\"text-center small mb-0\">&copy; 2026 Grand Vista Hotel. All rights reserved | Website Design by SLIIT-KdyUni-G54-2026-SEM-2 (FOC)</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
